### ISSUE TITLE
 Training process died with <Signals.SIGTERM: 15>

### ISSUE THREAD

**Issue by deyang2000** [yichen928/SparseFusion#25]
Hi, yichen,I used 2*3090 to train this model . 

Based on the previous discussion, I adjusted code:

samples_per_gpu=2,
workers_per_gpu=4,
 lr=0.000025,

The training lasted about six hours before it was terminated in the midnight with the following error:

2024-01-03 23:40:27,252 - mmdet - INFO - Epoch [1][10050/32025] lr: 3.228e-05, eta: 5 days, 11:34:54, time: 2.604, data_time: 0.014, memory: 15468, loss_heatmap: 0.0546, loss_heatmap_2d: 0.1132, layer_pts_0_loss_cls: 0.0870, layer_pts_0_loss_bbox: 0.4683, layer_pts_0_matched_ious: 0.5826, layer_fusion_0_loss_cls: 0.1132, layer_fusion_0_loss_bbox: 0.5391, layer_fusion_0_matched_ious: 0.5318, layer_img_0_loss_cls_2d: 0.2154, layer_img_0_loss_center_2d: 0.2669, layer_img_0_loss_depth_2d: 0.8491, layer_img_0_loss_dim_2d: 0.1206, layer_img_0_loss_rot_2d: 0.2580, layer_img_0_loss_vel_2d: 0.0665, layer_img_0_matched_ious_2d: 0.2209, layer_img_0_reg_bbox_2d: 1.5611, view_loss_cls: 0.2187, view_loss_bbox: 2.0935, view_matched_ious: 0.1762, loss: 5.4640, grad_norm: 6.8738
Traceback (most recent call last):
  File "/home/liyf/anaconda3/envs/sparse/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/liyf/anaconda3/envs/sparse/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/liyf/anaconda3/envs/sparse/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/liyf/anaconda3/envs/sparse/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/liyf/anaconda3/envs/sparse/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'configs/sparsefusion_nusc_voxel_LC_r50.py', '--launcher', 'pytorch', '--work-dir', 'work_dirs/sparsefusion_nusc_voxel_LC_r50']' died with <Signals.SIGTERM: 15>.

How can I solve this problem? Some research suggests it may be related to a lack of storage space.

I would appreciate it if you could take the time to answer this question!

**Comment by penggeniup** [comment]
I have the same question, have you solved it yet?
